FROM alpine:3.12.1

RUN apk update
RUN apk add bash openrc vim

RUN apk add influxdb
RUN mkdir -p /etc/influxdb
COPY influxdb.conf /etc/influxdb

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update
RUN apk add telegraf
RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/

COPY health /etc/health
COPY entrypoint.sh ./
CMD sh ./entrypoint.sh