FROM        alpine:3.11
RUN         apk update ; \
            apk add mysql mysql-client bash openrc
COPY        entrypoint.sh .
COPY        init_db.sh .
COPY        mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
COPY        my.cnf /etc/my.cnf
COPY        wordpressMorgan.sql .
RUN         chmod 777 entrypoint.sh
RUN         chmod 777 init_db.sh
#EXPOSE      3306

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update
RUN apk add telegraf
RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/


COPY health /etc/health
CMD         ./entrypoint.sh