FROM        alpine:3.11
RUN         apk update ; \
            apk add mysql mysql-client bash openrc
COPY        entrypoint.sh .
COPY        init_db.sh .
COPY        mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
COPY        my.cnf /etc/my.cnf
COPY        wordpressMorgan.sql .
RUN         chmod 777 entrypoint.sh
RUN         chmod 777 init_db.sh
#EXPOSE      3306
CMD         ./entrypoint.sh