FROM alpine:3.12.1

RUN apk update
RUN apk add bash nginx openrc vim
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add grafana
WORKDIR /usr/share/grafana
COPY sample.ini ./conf/custom.ini

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add telegraf
RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/


COPY entrypoint.sh .
CMD sh ./entrypoint.sh