FROM alpine:3.12.1

RUN apk update
RUN apk add bash nginx openrc vim
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add grafana
WORKDIR /usr/share/grafana
COPY sample.ini ./conf/custom.ini
COPY provisioning/datasources.yaml ./conf/provisioning/datasources/datasources.yaml

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add telegraf
RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/

COPY health /etc/health
COPY entrypoint.sh .
CMD sh ./entrypoint.sh