apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer 
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana-dep
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
