FROM alpine:latest

RUN apk update
RUN apk add bash nginx

RUN mkdir -p /run/nginx
RUN mkdir -p /data/www

COPY localhost.crt /etc/ssl/certs/localhost.crt 
COPY localhost.key /etc/ssl/private/localhost.key
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /data/www/index.html


EXPOSE 80
EXPOSE 443
STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
