FROM alpine:latest

RUN apk update
RUN apk add bash vsftpd

COPY entrypoint.sh .

COPY vsftpd.conf /etc/vsftpd/vsftpd.conf 
COPY localhost.crt /etc/vsftpd/vsftpd.crt
COPY localhost.key /etc/vsftpd/vsftpd.key

# ENV PASV_ADDRESS 192.168.99.137
# ENV PASV_ADDR_RESOLVE NO
# ENV PASV_ENABLE YES
# ENV PASV_MIN_PORT 13450
# ENV PASV_MAX_PORT 13450
# ENV XFERLOG_STD_FORMAT NO
# ENV LOG_STDOUT **Boolean**
# ENV FILE_OPEN_MODE 0666
# ENV LOCAL_UMASK 077
# ENV REVERSE_LOOKUP_ENABLE YES

RUN mkdir -p /data/www
COPY index.html /data/www/index.html

# EXPOSE 20 21 
# EXPOSE  13450

CMD sh ./entrypoint.sh

