FROM alpine:latest

RUN apk update
RUN apk add bash vsftpd

COPY entrypoint.sh .

COPY vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY localhost.crt /etc/vsftpd/vsftpd.crt
COPY localhost.key /etc/vsftpd/vsftpd.key

RUN mkdir -p /data/www
COPY index.html /data/www/index.html

EXPOSE 20 21 
#EXPOSE  13450-13500

CMD ./entrypoint.sh

