apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  labels:
    app: ftp
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - name: ftp1
    port: 20
    nodePort: 20
  - name: ftp2
    port: 21
    nodePort: 21
  - name: ftp3
    port: 13450
    nodePort: 13450
  selector:
    app: ftp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftp-dep
  labels:
    app: ftp
spec:
  selector:
    matchLabels:
      app: ftp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: ftp-container
          image: ftp-image:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 20
            name: ftp1
          - containerPort: 21
            name: ftp2
          - containerPort: 13450
            name: ftp3