apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: test-hello
  labels:
    app: test-pod
spec:
  selector:
    matchLabels:
      app: test-pod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: test-container
          image: hello-minikube:latest
          ports:
          - containerPort: 80