FROM alpine:latest
RUN apk update
RUN apk add openrc
RUN apk add nginx 

RUN mkdir -p /var/www/wordpress
# RUN apl php7-common php7-session php7-fpm php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom
RUN apk add php7-common php7-session php7-fpm php7-mcrypt php7-soap php7-openssl php7-gmp php7-pdo_odbc php7-json php7-dom php7-pdo php7-zip php7-mysqli php7-sqlite3 php7-apcu php7-pdo_pgsql php7-bcmath php7-gd php7-odbc php7-pdo_mysql php7-pdo_sqlite php7-gettext php7-xmlreader php7-xmlrpc php7-bz2 php7-iconv php7-pdo_dblib php7-curl php7-ctype


# COPY testphp.php /var/www/index.php
# COPY index.html /var/www/index.html
RUN cd /var/www \
    && wget https://wordpress.org/latest.tar.gz \
    && tar -xzvf latest.tar.gz \
    && rm latest.tar.gz
COPY wp-config.php /var/www/wordpress/wp-config.php
COPY entrypoint.sh /etc/entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf
RUN chown -R nginx:nginx /var/www/wordpress && chmod -R 777 /var/www/wordpress

EXPOSE 80
CMD sh /etc/entrypoint.sh