apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer 
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: wp
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wp-dep
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp-container
        image: wp-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
              - cat
              - /etc/health
          initialDelaySeconds: 1
          periodSeconds: 1
