FROM alpine:latest
# install wget, nginx, mysql
RUN apk add openrc 
RUN apk add mysql mysql-client
COPY entrypoint.sh /etc/entrypoint.sh
COPY config.sql /etc/config.sql
VOLUME ["/var/lib/mysql"]

EXPOSE 3306

CMD sh /etc/entrypoint.sh
