FROM alpine:latest
# install wget, nginx, mysql
RUN apk add openrc 
RUN apk add mysql mysql-client
COPY entrypoint.sh /etc/entrypoint.sh
COPY config.sql /etc/config.sql
#COPY my.cnf /etc/my.cnf
COPY mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
VOLUME ["/var/lib/mysql"]
VOLUME ["/sys/fs/cgroup"]

EXPOSE 3306

CMD sh /etc/entrypoint.sh
