apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 3306
    nodePort: 3306
  selector:
    app: mysql
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   labels:
#     app: mysql
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# ---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # volumes:
      #   - name: mysql-pv-storage
      #     persistentVolumeClaim:
      #       claimName: mysql-pv-claim
      containers:
      - name: mysql-container
        image: mysql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        # volumeMounts:
        #   - mountPath: "/var/lib/mysql"
        #     name: mysql-pv-storage