FROM alpine:3.12.1

RUN apk update
RUN apk add bash nginx

RUN mkdir -p /run/nginx
RUN mkdir -p /data/www

COPY localhost.crt /etc/ssl/certs/localhost.crt 
COPY localhost.key /etc/ssl/private/localhost.key
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /data/www/index.html

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
