FROM alpine:3.12.1

RUN apk update
RUN apk add bash nginx openrc

RUN mkdir -p /run/nginx
RUN mkdir -p /data/www

COPY localhost.crt /etc/ssl/certs/localhost.crt 
COPY localhost.key /etc/ssl/private/localhost.key
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /data/www/index.html

RUN apk add vim telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/

COPY health /etc/health
COPY entrypoint.sh ./entrypoint.sh
CMD sh ./entrypoint.sh
