FROM alpine:3.12.1

RUN apk update
RUN apk add bash nginx openrc

RUN mkdir -p /run/nginx
RUN mkdir -p /data/www

COPY localhost.crt /etc/ssl/certs/localhost.crt 
COPY localhost.key /etc/ssl/private/localhost.key
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /data/www/index.html

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add telegraf
RUN mkdir /etc/telegraf && rm /etc/telegraf.conf
COPY telegraf.conf /etc/telegraf/

COPY health /etc/health
COPY entrypoint.sh ./entrypoint.sh
CMD sh ./entrypoint.sh
